#!/bin/sh 
export BSPWM_CONFIG="$HOME/.config/bspwm"

# Launch keybindind Daemon
sxhkd &

# Launch compton
compton --config ~/.config/compton/compton.conf -b &

# Launch dunst notifications
dunst &

# Launch xbanish
xbanish &

# Launch panel
# [ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
# pkill -x panel; sh /home/chrx/.config/bspwm/panel/panel &

# Launch polybar
polybar bar &

bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor eDP1 -d 1 2 3 4 5 6 7

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio           0.62
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focus_by_distance     true

bspc config normal_border_color '#928374'
bspc config focused_border_color '#d65d0e'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'

# wanna find out window name? use 'xprop'!!!
bspc rule -a "Xfce4-terminal" desktop='^1' follow=on
bspc rule -a "urxvt" desktop='^1' follow=on
bspc rule -a "Brave-browser" desktop='^2' follow=on
bspc rule -a "Firefox" desktop='^2' follow=on
bspc rule -a "Vivaldi-stable" desktop='^2' follow=on
bspc rule -a "Code" desktop='^3' follow=on
bspc rule -a "TelegramDesktop" desktop='^5' follow=on
bspc rule -a "Pcmanfm" desktop='^6' follow=on
bspc rule -a "Insync" desktop='^7' 
bspc rule -a "Standard Notes" desktop='^3' 

# Autostart
$BSPWM_CONFIG/autostart &
